### ISSUE TITLE
Can this extension be on it's own schema like net plugin ?

### ISSUE THREAD

**Issue by riderx** [mansueli/supa_queue#1]
it could be nice to isolate this to 'supa_queue'  schema instead of public

**Comment by mansueli** [comment]
Hey @riderx,

I didn't test this, but it should be possible with:

```sql

create schema supa_queue;
select dbdev.install('mansueli-supa_queue');
create extension "mansueli-supa_queue"
    schema supa_queue
    version '1.0.3';
    
```

Let me know if you face any issues running in a different schema.

**Comment by mansueli** [comment]
Closing this as I didn't hear about about any issues. Feel free to open again if you face issues.

**Comment by riderx** [comment]
Sorry I didn’t saw your answer thanks for this !
